import HomeButton from '@/components/HomeButton';
import './index.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export const dynamicParams = true;

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <HomeButton />
        {children}
      </body>
    </html>
  );
}
